Repository brave-intl/publishers, pull requests merged in 2023-12, with the labels that each got.

#4281 Feat/updates dec 23
  Gemfile
  Gemfile.lock
  app/models/channel.rb
  package.json
  yarn.lock
Labels: needs-security-review

#4284 fix vertical alignment on channel page dropdown
  app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
Labels: needs-security-review

#4285 Admins have longer login
  app/javascript/packs/SettingsPage.tsx
  app/models/publisher.rb
Labels: needs-security-review

#4287 Add validate endpoint service class
  app/models/gemini_connection.rb
  app/services/gemini/get_validation_service.rb
  test/models/gemini_connection_test.rb
  test/services/payout/gemini_get_validation_service_test.rb
Labels: needs-security-review, unverified-commits

#4288 switch all references to main nets
  app/controllers/public_channel_controller.rb
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/javascript/views/publicChannelPage/batAbi.json
Labels: unverified-commits

#4289 Prod release 12-11-23
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/pages/crypto-wallets.scss
  app/controllers/public_channel_controller.rb
  app/javascript/locale/en.ts
  app/javascript/packs/CryptoWalletServices.jsx
  app/javascript/packs/SettingsPage.tsx
  app/javascript/views/cryptoWalletServices/CryptoPrivacyModal.jsx
  app/javascript/views/cryptoWalletServices/CryptoWalletServices.jsx
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
  app/javascript/views/publicChannelPage/batAbi.json
  app/models/channel.rb
  app/models/gemini_connection.rb
  app/models/publisher.rb
  app/services/gemini/get_validation_service.rb
  nextjs/package-lock.json
  package.json
  test/features/site_channel_verification_test.rb
  test/jobs/two_factor_authentication_removal_job_test.rb
  test/models/gemini_connection_test.rb
  test/services/payout/gemini_get_validation_service_test.rb
  yarn.lock
Labels: unverified-commits

#4290 add https to web3 url
  app/jobs/cache/browser_channels/responses_for_prefix.rb
Labels: unverified-commits

#4291 Prod Release 12-12-23
  app/jobs/cache/browser_channels/responses_for_prefix.rb
Labels: unverified-commits

#4292 Ensure suspensions always add a previously deleted record
  app/models/publisher.rb
  app/models/publisher_status_update.rb
  test/controllers/api/v1/publishers_controller_test.rb
Labels: unverified-commits

#4293 make blockhash queries consistent
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
Labels: unverified-commits

#4294 Prod Release 12-13-23
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/models/publisher.rb
  app/models/publisher_status_update.rb
  test/controllers/api/v1/publishers_controller_test.rb
Labels: unverified-commits

#4295 fix cut/paste error
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
Labels: unverified-commits

#4296 Prod Release II 12-13-23
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
Labels: unverified-commits

#4297 Update styling on several components of the public channel page
  app/assets/images/dollar_sign.svg
  app/assets/images/purple_verified.svg
  app/javascript/locale/en.ts
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/javascript/views/publicChannelPage/PublicChannelPage.jsx
  app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
Labels: needs-security-review, unverified-commits

#4298 Prod Release 12-19-23
  app/assets/images/dollar_sign.svg
  app/assets/images/purple_verified.svg
  app/javascript/locale/en.ts
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/javascript/views/publicChannelPage/PublicChannelPage.jsx
  app/javascript/views/publicChannelPage/PublicChannelPageStyle.js
Labels: needs-security-review, unverified-commits

#4299 override allowed_countries list for gemini
  app/models/gemini_connection.rb
  test/fixtures/gemini_connections.yml
Labels: unverified-commits

#4300 Prod Release 12-20-23
  app/models/gemini_connection.rb
  test/fixtures/gemini_connections.yml
Labels: unverified-commits

#4302 Prod Release 12-21-23
  app/javascript/views/walletServices/braveConnection/NotConnected.tsx
  app/jobs/cache/browser_channels/responses_for_prefix.rb
Labels: unverified-commits
