Repository brave-intl/publishers, pull requests merged in 2024-05, with the labels that each got.

#4433 updated language for the add a channel info box
  config/locales/en.yml
Labels: unverified-commits

#4432 remove case file upload
  app/javascript/packs/case.jsx
  app/views/publishers/cases/new.html.slim
Labels: unverified-commits

#4431 remove babel-preset-react
  app/javascript/packs/banner_editor.jsx
  app/javascript/publishers/home.js
  nextjs/package.json
  nextjs/src/app/[locale]/publishers/layout.tsx
  nextjs/src/app/[locale]/publishers/settings/page.tsx
  package.json
  yarn.lock
Labels: unverified-commits

#4428 Update sidekiq
  .vscode/settings.json
  Gemfile.lock
  app/javascript/packs/banner_editor.jsx
  app/javascript/publishers/home.js
  app/views/static/index.html
  babel.config.js
  config/webpack/webpack.config.js
  package.json
  public/asset-manifest.json
  public/creators-landing/package.json
  public/creators-landing/yarn.lock
  public/preview.png
  public/static/css/main.99b73499.css
  public/static/css/main.99b73499.css.map
  yarn.lock
Labels: puLL-Merge

#4434 add usdc options
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  app/assets/images/usdc_icon.svg
  app/controllers/public_channel_controller.rb
  app/javascript/locale/en.ts
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
  app/javascript/views/publicChannelPage/erc20Abi.json
  app/javascript/views/publicChannelPage/goerliBatAbi.json
  config/secrets.yml
  package.json
  test/cassettes/test_can_display_description_and_title.yml
  test/cassettes/test_can_select_different_currencies.yml
  test/cassettes/test_can_update_amounts.yml
  test/features/public_page_test.rb
  test/test_helper.rb
  yarn.lock
Labels: unverified-commits, puLL-Merge

#4442 add adjustments for usdc-solana
  app/javascript/views/publicChannelPage/CryptoPaymentWidget.jsx
Labels: unverified-commits
